const patterns = [
  {
    name: 'Bestway 1705 Busy Bee',
    craftType: 'Knitting',
    needleSize: '2',
    yarnWeight: '3',
    difficulty: 'Advanced',
    imgSrc: './images/pattern1.png',
  },
  {
    name: "Munrospun Lady's Blouse",
    craftType: 'Knitting',
    needleSize: '6',
    yarnWeight: '4',
    difficulty: 'Intermediate',
    imgSrc: './images/pattern2.png',
  },
  {
    name: 'Fancy Waistcoat',
    craftType: 'Knitting',
    needleSize: '4',
    yarnWeight: '3',
    difficulty: 'Beginner-Intermediate',
    imgSrc: './images/pattern3.png',
  },
  {
    name: 'Shepherd 242 Womans Jacket',
    craftType: 'Crochet',
    needleSize: '4',
    yarnWeight: '5',
    difficulty: 'Beginner',
    imgSrc: './images/pattern4.png',
  },
  {
    name: 'Bestway 1433 Crochet Blouse',
    craftType: 'Crochet',
    needleSize: '2',
    yarnWeight: '3',
    difficulty: 'Beginner-Intermediate',
    imgSrc: './images/pattern4.png',
  },
]
